# https://gitlab.webhare.com/webhare/nginx-proxy/pipelines

stages:
  - build
  - deploy

# the TAG variable is also used by the docker.sh script
variables:
  TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

after_script:
  - docker logout $CI_REGISTRY
  - docker logout

buildmachine:
  stage: build
  script:
    - ./docker.sh build
    - docker push $TAG

taggedpush:
  stage: deploy
  except:
    - schedules
  script:
    - echo $DOCKERHUB_REGISTRY_PASSWORD | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker pull $TAG
    - docker tag $TAG webhare/proxy:$CI_COMMIT_REF_NAME
    - docker push webhare/proxy:$CI_COMMIT_REF_NAME
