#!/bin/bash
source "$WEBHAREPROXY_FSROOT/opt/container/env.sh" || exit 150
exec "${WEBHAREPROXY_CODEROOT}/nginx-proxy.js" --configfolder="$WEBHAREPROXY_DATAROOT" --port="$WEBHAREPROXY_MGMT_HTTPS" --localhostport="$WEBHAREPROXY_MGMT_HTTP"
