; see https://www.stunnel.org/config_unix.html

setuid = nobody
setgid = nobody
foreground = quiet
options = -NO_SSLv3
; disable pids, foreground mode anyway
pid =

; using a separate dir because 'rm' doesn't always work on overlay
include = /etc/stunnel/conf.out
