#!/bin/bash
set -x
mkdir -p "${WEBHAREPROXY_DATAROOT}/etc/ssl_config" "${WEBHAREPROXY_DATAROOT}/cache/" "${WEBHAREPROXY_DATAROOT}/log/"

function ensurekey() {
  local BASENAME BASEPATH HOSTNAME

  BASENAME="$1"
  BASEPATH="${WEBHAREPROXY_DATAROOT}etc/ssl_config/${BASENAME}"
  HOSTNAME="$2"

  if [ ! -f "${BASEPATH}.key" ] && [ ! -f  "${BASEPATH}.crt" ]; then
    echo "*** 50_setup_nginx_proxy.sh: Generating certificate for $HOSTNAME"
    mv "${BASEPATH}".key{,.bak} 2>/dev/null #ignore errors,just a backup
    mv "${BASEPATH}".crt{,.bak} 2>/dev/null

    cd "${WEBHAREPROXY_DATAROOT}etc/ssl_config" || exit 1
    openssl genrsa -out "${BASENAME}.key" 2048
    echo -e "NL\nOverijssel\nEnschede\nWebHare\n\n$(hostname -f)\n" | openssl req -new -x509 -nodes -sha1 -days 365 -key "${BASENAME}.key" 2>/dev/null > "${BASENAME}.crt"
  fi
}

ensurekey ssl "$(hostname -f)"
# Do the WEBHAREPROXY_ADMINHOSTNAME keys exist?
if [ -n "$WEBHAREPROXY_ADMINHOSTNAME" ]; then
  ensurekey "${WEBHAREPROXY_ADMINHOSTNAME}" "${WEBHAREPROXY_ADMINHOSTNAME}"
fi

echo "** Updating/creating initial configuration"
"${WEBHAREPROXY_CODEROOT}src/nginx-proxy.js" --regenerate

while [ ! -f "$WEBHAREPROXY_DATAROOT"/etc/nginx.conf ]; do
  echo "nginx is waiting for its config file to appear..."
  sleep 300
done

exec "$WEBHAREPROXY_NGINX" -c "$WEBHAREPROXY_DATAROOT"/etc/nginx.conf -g 'daemon off;'
