[supervisord]
nodaemon=true               ; (start in foreground if true;default false)

logfile=/var/log/supervisor/supervisord.log  ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB       ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10          ; (num of main logfile rotation backups;default 10)
loglevel=info               ; (log level;default info; others: debug,warn,trace)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
minfds=1024                 ; (min. avail startup file descriptors;default 1024)
minprocs=200                ; (min. avail process descriptors;default 200)

[program:nginx]
command=/usr/sbin/nginx -c /opt/webhare-proxy-data/etc/nginx.conf -g 'daemon off;'
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:configserver]
command=/opt/webhare-nginx-proxy/src/nginx-proxy.js --configfolder=/opt/webhare-proxy-data --port=5443
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

; ADDME only need to start this on dev instances? but it's probably nice for hotfixing too
[program:codewatch]
directory=/opt/webhare-nginx-proxy/
command=/opt/webhare-nginx-proxy/node_modules/.bin/webpack --config src/webpack-production.config.js --progress --colors --watch
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
